//footballscores\client\src\components\test\TableData.js

const data = 
[
    {
        "Position": 1,
        "Club": "Liverpool",
        "Played": 12,
        "Won": 10,
        "Drawn": 1,
        "Lost": 1,
        "GF": 24,
        "GA": 8,
        "GD": 16,
        "Points": 31
    },
    {
        "Position": 2,
        "Club": "Manchester City",
        "Played": 12,
        "Won": 7,
        "Drawn": 2,
        "Lost": 3,
        "GF": 22,
        "GA": 17,
        "GD": 5,
        "Points": 23
    },
    {
        "Position": 3,
        "Club": "Chelsea",
        "Played": 12,
        "Won": 6,
        "Drawn": 4,
        "Lost": 2,
        "GF": 23,
        "GA": 14,
        "GD": 9,
        "Points": 22
    },
    {
        "Position": 4,
        "Club": "Arsenal",
        "Played": 12,
        "Won": 6,
        "Drawn": 4,
        "Lost": 2,
        "GF": 21,
        "GA": 12,
        "GD": 9,
        "Points": 22
    },
    {
        "Position": 5,
        "Club": "Brighton and Hove Albion",
        "Played": 12,
        "Won": 6,
        "Drawn": 4,
        "Lost": 2,
        "GF": 21,
        "GA": 16,
        "GD": 5,
        "Points": 22
    },
    {
        "Position": 6,
        "Club": "Tottenham Hotspur",
        "Played": 12,
        "Won": 6,
        "Drawn": 1,
        "Lost": 5,
        "GF": 27,
        "GA": 13,
        "GD": 14,
        "Points": 19
    },
    {
        "Position": 7,
        "Club": "Nottingham Forest",
        "Played": 12,
        "Won": 5,
        "Drawn": 4,
        "Lost": 3,
        "GF": 15,
        "GA": 13,
        "GD": 2,
        "Points": 19
    },
    {
        "Position": 8,
        "Club": "Aston Villa",
        "Played": 12,
        "Won": 5,
        "Drawn": 4,
        "Lost": 3,
        "GF": 19,
        "GA": 19,
        "GD": 0,
        "Points": 19
    },
    {
        "Position": 9,
        "Club": "Fulham",
        "Played": 12,
        "Won": 5,
        "Drawn": 3,
        "Lost": 4,
        "GF": 17,
        "GA": 17,
        "GD": 0,
        "Points": 18
    },
    {
        "Position": 10,
        "Club": "Newcastle United",
        "Played": 12,
        "Won": 5,
        "Drawn": 3,
        "Lost": 4,
        "GF": 13,
        "GA": 13,
        "GD": 0,
        "Points": 18
    },
    {
        "Position": 11,
        "Club": "Brentford",
        "Played": 12,
        "Won": 5,
        "Drawn": 2,
        "Lost": 5,
        "GF": 22,
        "GA": 22,
        "GD": 0,
        "Points": 17
    },
    {
        "Position": 12,
        "Club": "Manchester United",
        "Played": 12,
        "Won": 4,
        "Drawn": 4,
        "Lost": 4,
        "GF": 13,
        "GA": 13,
        "GD": 0,
        "Points": 16
    },
    {
        "Position": 13,
        "Club": "Bournemouth",
        "Played": 12,
        "Won": 4,
        "Drawn": 3,
        "Lost": 5,
        "GF": 16,
        "GA": 17,
        "GD": -1,
        "Points": 15
    },
    {
        "Position": 14,
        "Club": "West Ham United",
        "Played": 12,
        "Won": 4,
        "Drawn": 3,
        "Lost": 5,
        "GF": 15,
        "GA": 19,
        "GD": -4,
        "Points": 15
    },
    {
        "Position": 15,
        "Club": "Everton",
        "Played": 12,
        "Won": 2,
        "Drawn": 5,
        "Lost": 5,
        "GF": 10,
        "GA": 17,
        "GD": -7,
        "Points": 11
    },
    {
        "Position": 16,
        "Club": "Leicester City",
        "Played": 12,
        "Won": 2,
        "Drawn": 4,
        "Lost": 6,
        "GF": 15,
        "GA": 23,
        "GD": -8,
        "Points": 10
    },
    {
        "Position": 17,
        "Club": "Wolverhampton Wanderers",
        "Played": 12,
        "Won": 2,
        "Drawn": 3,
        "Lost": 7,
        "GF": 20,
        "GA": 28,
        "GD": -8,
        "Points": 9
    },
    {
        "Position": 18,
        "Club": "Ipswich Town",
        "Played": 12,
        "Won": 1,
        "Drawn": 6,
        "Lost": 5,
        "GF": 13,
        "GA": 23,
        "GD": -10,
        "Points": 9
    },
    {
        "Position": 19,
        "Club": "Crystal Palace",
        "Played": 12,
        "Won": 1,
        "Drawn": 5,
        "Lost": 6,
        "GF": 10,
        "GA": 17,
        "GD": -7,
        "Points": 8
    },
    {
        "Position": 20,
        "Club": "Southampton",
        "Played": 12,
        "Won": 1,
        "Drawn": 1,
        "Lost": 10,
        "GF": 9,
        "GA": 24,
        "GD": -15,
        "Points": 4
    }
]

export default data;